addons:
   sonarcloud:
     organization: "asus-aics"
     token:
       secure: $SONAR_TOKEN
jobs:
   include:
     - stage: "Run Tests & SonarCloud Analysis"
       script:
         - npm test
         - sonar-scanner -Dsonar.projectKey=$SONAR_PROJECT_KEY