addons:
   sonarcloud:
     organization: "davidhdez98"
     token:
       secure: $SONAR_TOKEN
jobs:
   include:
     - stage: "Run Tests & SonarCloud Analysis"
       script:
         - sonar-scanner -Dsonar.projectKey=davidhdez98_software-quality